version: "3.8"

services:
  geoserver:
    image: docker.osgeo.org/geoserver:2.26.2
    container_name: geoserver
    ports:
      - "8000:8000"
    environment:
      - GEOSERVER_DATA_DIR=/var/local/geoserver
      - POSTGIS_HOST=postgis
      - POSTGIS_DB=geodb
      - POSTGIS_USER=geouser
      - POSTGIS_PASSWORD=geopass
    networks:
      - red01
    depends_on:
      - postgis
    restart: unless-stopped

  postgis:
    image: postgis/postgis:latest
    container_name: postgis
    environment:
      - POSTGRES_DB=geodb
      - POSTGRES_USER=geouser
      - POSTGRES_PASSWORD=geopass
    ports:
      - "5433:5432"
    restart: unless-stopped

  backend-stn:
    build:
      context: /backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "5005:5005"
    container_name: backend-stn

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./html:/usr/share/nginx/html:ro
    networks:
      - red01
    restart: unless-stopped
networks:
  red01:
    driver: bridge
